name: payment_gateway_server
description: A Library Full Package Template
version: 0.0.0
homepage: https://github.com/azkadev/payment_gateway
repository: https://github.com/azkadev/payment_gateway
issue_tracker: https://github.com/azkadev/payment_gateway/issues 
documentation: https://youtube.com/@azkadev
funding:
  - https://github.com/sponsors/azkadev


platforms:
 android:
 ios:
 linux:
 macos:
 web:
 windows:

# topics:
#   - payment_gateway
#   - payment_gateway_flutter
#   - payment_gateway_dart
environment:
  sdk: ^3.2.3

# Add regular dependencies here.
# dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
